import { precacheAndRoute } from 'workbox-precaching'
import { set, get, del } from 'idb-keyval'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Push notification handler
self.addEventListener('push', (event) => {
  if (!event.data) return

  let data
  try {
    data = event.data.json()
  } catch {
    data = {
      title: 'Streak Life',
      body: event.data.text(),
    }
  }

  const options = {
    body: data.body || '',
    icon: data.icon || '/icons/icon-192.png',
    badge: data.badge || '/icons/badge-72.png',
    vibrate: [100, 50, 100],
    data: data.data || { url: '/' },
    actions: [
      { action: 'done', title: '✅ Feito' },
      { action: 'dismiss', title: 'Dispensar' },
    ],
    tag: data.tag || 'streak-life-reminder',
    renotify: true,
  }

  event.waitUntil(
    self.registration.showNotification(data.title || 'Streak Life', options)
  )
})

// Notification click handler
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  if (event.action === 'dismiss') {
    return;
  }

  if (event.action === 'done') {
    event.waitUntil((async () => {
      const data = event.notification.data;
      if (!data || !data.habitId) return;

      const token = await get('sb_access_token');
      const userId = await get('sb_user_id');
      const supabaseUrl = await get('sb_url');
      const anonKey = await get('sb_anon_key');

      if (token && userId && supabaseUrl && anonKey) {
        try {
          // Use the user's timezone (stored when auth was set) to determine today
          const timezone = await get('sb_timezone') || 'America/Fortaleza';
          let dateStr;
          if (data.date) {
            dateStr = data.date;
          } else {
            try {
              const parts = new Intl.DateTimeFormat('en-CA', {
                timeZone: timezone,
                year: 'numeric', month: '2-digit', day: '2-digit',
              }).formatToParts(new Date());
              const get2 = t => parts.find(p => p.type === t)?.value;
              dateStr = `${get2('year')}-${get2('month')}-${get2('day')}`;
            } catch {
              dateStr = new Date().toISOString().split('T')[0];
            }
          }

          const response = await fetch(`${supabaseUrl}/functions/v1/habit-mark-done`, {
            method: 'POST',
            headers: {
              'apikey': anonKey,
              'Authorization': `Bearer ${token}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              habitId: data.habitId,
              data: dateStr,
            })
          });

          if (!response.ok) {
            throw new Error(`habit-mark-done failed: ${response.status}`);
          }
        } catch (e) {
          console.error('Failed to mark habit as done', e);
        }
      }
    })());
    return;
  }

  const urlToOpen = event.notification.data?.url || '/'

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      // Focus existing window if available
      for (const client of clients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus()
          client.navigate(urlToOpen)
          return
        }
      }
      // Otherwise open a new window
      return self.clients.openWindow(urlToOpen)
    })
  )
})

// Skip waiting on update and auth messages
self.addEventListener('message', (event) => {
  if (event.data) {
    if (event.data.type === 'SKIP_WAITING') {
      self.skipWaiting()
    } else if (event.data.type === 'SET_SUPABASE_AUTH') {
      set('sb_access_token', event.data.access_token)
      set('sb_user_id', event.data.user_id)
      set('sb_url', event.data.supabase_url)
      set('sb_anon_key', event.data.supabase_anon_key)
      if (event.data.timezone) set('sb_timezone', event.data.timezone)
    } else if (event.data.type === 'CLEAR_SUPABASE_AUTH') {
      del('sb_access_token')
      del('sb_user_id')
      del('sb_url')
      del('sb_anon_key')
      del('sb_timezone')
    }
  }
})
